Repository Team-Pickify/backend, pull requests merged in 2025-02, with the labels that each got.

#43 [Feat] Place CRUD
  build.gradle
  src/main/java/com/pickyfy/pickyfy/config/AwsConfig.java
  src/main/java/com/pickyfy/pickyfy/config/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/pickyfy/pickyfy/config/OctetStreamReadMsgConverter.java
  src/main/java/com/pickyfy/pickyfy/config/WebConfig.java
  src/main/java/com/pickyfy/pickyfy/domain/Place.java
  src/main/java/com/pickyfy/pickyfy/domain/PlaceImage.java
  src/main/java/com/pickyfy/pickyfy/repository/PlaceRepository.java
  src/main/java/com/pickyfy/pickyfy/service/AdminService.java
  src/main/java/com/pickyfy/pickyfy/service/AdminServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/PlaceServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/S3Service.java
  src/main/java/com/pickyfy/pickyfy/web/controller/PlaceController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/PlaceControllerApi.java
  src/main/java/com/pickyfy/pickyfy/web/dto/request/PlaceCreateRequest.java
  src/main/java/com/pickyfy/pickyfy/web/dto/request/PlaceSearchRequest.java
  src/main/resources/application-bucket.yml
Labels: ✨ feature

#56 [Refactor] Place 모든 기능 수정 및 더미데이터 추가
  src/main/java/com/pickyfy/pickyfy/config/SwaggerConfig.java
  src/main/java/com/pickyfy/pickyfy/domain/Place.java
  src/main/java/com/pickyfy/pickyfy/domain/PlaceCategory.java
  src/main/java/com/pickyfy/pickyfy/domain/PlaceMagazine.java
  src/main/java/com/pickyfy/pickyfy/repository/PlaceSavedPlaceRepository.java
  src/main/java/com/pickyfy/pickyfy/service/AdminService.java
  src/main/java/com/pickyfy/pickyfy/service/AdminServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/PlaceService.java
  src/main/java/com/pickyfy/pickyfy/service/PlaceServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/web/controller/PlaceController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/PlaceControllerApi.java
  src/main/java/com/pickyfy/pickyfy/web/dto/request/PlaceCreateRequest.java
Labels: ♻️ refactor

#58 feat/주변 플레이스 조회
  build.gradle
  src/main/java/com/pickyfy/pickyfy/config/QuerydslConfig.java
  src/main/java/com/pickyfy/pickyfy/repository/PlaceRepository.java
  src/main/java/com/pickyfy/pickyfy/repository/PlaceRepositoryCustom.java
  src/main/java/com/pickyfy/pickyfy/repository/PlaceRepositoryImpl.java
  src/main/java/com/pickyfy/pickyfy/service/MagazineServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/PlaceService.java
  src/main/java/com/pickyfy/pickyfy/service/PlaceServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/web/controller/MagazineController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/PlaceController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/PlaceControllerApi.java
  src/main/java/com/pickyfy/pickyfy/web/dto/NearbyPlaceSearchCondition.java
  src/main/java/com/pickyfy/pickyfy/web/dto/request/MagazineCreateRequest.java
  src/main/java/com/pickyfy/pickyfy/web/dto/request/MagazineUpdateRequest.java
  src/main/java/com/pickyfy/pickyfy/web/dto/request/NearbyPlaceSearchRequest.java
  src/main/java/com/pickyfy/pickyfy/web/dto/response/NearbyPlaceResponse.java
  src/test/java/com/pickyfy/pickyfy/repository/PlaceRepositoryImplTest.java
  src/test/java/com/pickyfy/pickyfy/service/MagazineServiceImplTest.java
Labels: ✨ feature

#65 [Bug] Place 삭제 API 수정
  src/main/java/com/pickyfy/pickyfy/domain/Place.java
  src/main/java/com/pickyfy/pickyfy/domain/SavedPlace.java
  src/main/java/com/pickyfy/pickyfy/service/PlaceServiceImpl.java
Labels: 🐛 bug

#61 [Refactor] 유저 프로필 이미지 수정 / 에러 코드 / 파일 위치 리팩토링
  src/main/java/com/pickyfy/pickyfy/apiPayload/code/BaseCode.java
  src/main/java/com/pickyfy/pickyfy/apiPayload/code/BaseErrorCode.java
  src/main/java/com/pickyfy/pickyfy/apiPayload/code/dto/ErrorResponseDTO.java
  src/main/java/com/pickyfy/pickyfy/apiPayload/code/dto/ResponseDTO.java
  src/main/java/com/pickyfy/pickyfy/common/config/AwsConfig.java
  src/main/java/com/pickyfy/pickyfy/common/config/MailConfig.java
  src/main/java/com/pickyfy/pickyfy/common/config/MultipartJackson2HttpMessageConverter.java
  src/main/java/com/pickyfy/pickyfy/common/config/OctetStreamReadMsgConverter.java
  src/main/java/com/pickyfy/pickyfy/common/config/QuerydslConfig.java
  src/main/java/com/pickyfy/pickyfy/common/config/RedisConfig.java
  src/main/java/com/pickyfy/pickyfy/common/config/SecurityConfig.java
  src/main/java/com/pickyfy/pickyfy/common/config/SwaggerConfig.java
  src/main/java/com/pickyfy/pickyfy/common/config/WebConfig.java
  src/main/java/com/pickyfy/pickyfy/common/util/JwtUtil.java
  src/main/java/com/pickyfy/pickyfy/common/util/RedisUtil.java
  src/main/java/com/pickyfy/pickyfy/common/util/TokenExtractor.java
  src/main/java/com/pickyfy/pickyfy/domain/Place.java
  src/main/java/com/pickyfy/pickyfy/domain/PlaceMagazine.java
  src/main/java/com/pickyfy/pickyfy/domain/SavedPlace.java
  src/main/java/com/pickyfy/pickyfy/domain/User.java
  src/main/java/com/pickyfy/pickyfy/exception/DuplicateResourceException.java
  src/main/java/com/pickyfy/pickyfy/exception/GeneralException.java
  src/main/java/com/pickyfy/pickyfy/exception/GlobalExceptionHandler.java
  src/main/java/com/pickyfy/pickyfy/exception/handler/ExceptionHandler.java
  src/main/java/com/pickyfy/pickyfy/service/AdminService.java
  src/main/java/com/pickyfy/pickyfy/service/AdminServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/CategoryServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/EmailServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/MagazineServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/PlaceServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/S3Service.java
  src/main/java/com/pickyfy/pickyfy/service/UserService.java
  src/main/java/com/pickyfy/pickyfy/service/UserServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/web/apiResponse/common/ApiResponse.java
  src/main/java/com/pickyfy/pickyfy/web/apiResponse/common/BaseErrorCode.java
  src/main/java/com/pickyfy/pickyfy/web/apiResponse/common/BaseSuccessCode.java
  src/main/java/com/pickyfy/pickyfy/web/apiResponse/common/StatusCode.java
  src/main/java/com/pickyfy/pickyfy/web/apiResponse/error/ErrorResponse.java
  src/main/java/com/pickyfy/pickyfy/web/apiResponse/error/ErrorStatus.java
  src/main/java/com/pickyfy/pickyfy/web/apiResponse/success/SuccessResponse.java
  src/main/java/com/pickyfy/pickyfy/web/apiResponse/success/SuccessStatus.java
  src/main/java/com/pickyfy/pickyfy/web/controller/AdminController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/AdminControllerApi.java
  src/main/java/com/pickyfy/pickyfy/web/controller/CategoryController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/CategoryControllerApi.java
  src/main/java/com/pickyfy/pickyfy/web/controller/EmailController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/EmailControllerApi.java
  src/main/java/com/pickyfy/pickyfy/web/controller/MagazineController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/MagazineControllerApi.java
  src/main/java/com/pickyfy/pickyfy/web/controller/PlaceController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/PlaceControllerApi.java
  src/main/java/com/pickyfy/pickyfy/web/controller/UserController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/UserControllerApi.java
  src/main/java/com/pickyfy/pickyfy/web/dto/request/PasswordResetRequest.java
  src/main/java/com/pickyfy/pickyfy/web/dto/request/UserUpdateRequest.java
  src/main/java/com/pickyfy/pickyfy/web/dto/response/UserUpdateResponse.java
Labels: ♻️ refactor

#70 [Bug] Place update 수정 및 placeSearchResponse dto 수정
  src/main/java/com/pickyfy/pickyfy/service/PlaceService.java
  src/main/java/com/pickyfy/pickyfy/service/PlaceServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/web/dto/response/PlaceSearchResponse.java
Labels: 🐛 bug

#63 [Refactor] 블랙리스트 검증 로직 삭제 및 로그아웃 API 리팩토링
  src/main/java/com/pickyfy/pickyfy/auth/filter/CustomLoginFilter.java
  src/main/java/com/pickyfy/pickyfy/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/pickyfy/pickyfy/common/Constant.java
  src/main/java/com/pickyfy/pickyfy/common/util/JwtUtil.java
  src/main/java/com/pickyfy/pickyfy/common/util/RedisUtil.java
  src/main/java/com/pickyfy/pickyfy/service/AdminService.java
  src/main/java/com/pickyfy/pickyfy/service/AdminServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/AuthService.java
  src/main/java/com/pickyfy/pickyfy/service/AuthServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/EmailServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/UserService.java
  src/main/java/com/pickyfy/pickyfy/service/UserServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/web/controller/AdminController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/AdminControllerApi.java
  src/main/java/com/pickyfy/pickyfy/web/controller/AuthController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/AuthControllerApi.java
  src/main/java/com/pickyfy/pickyfy/web/controller/UserController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/UserControllerApi.java
Labels: ♻️ refactor

#76 [Fix]: category와 로직 통일
  src/main/java/com/pickyfy/pickyfy/service/PlaceServiceImpl.java
Labels: 🐛 bug

#68 [Refactor]: 비밀번호 재설정 리팩토링
  src/main/java/com/pickyfy/pickyfy/service/UserServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/web/controller/UserController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/UserControllerApi.java
  src/main/java/com/pickyfy/pickyfy/web/dto/request/PasswordResetRequest.java
Labels: ♻️ refactor

#72 [bug] 매거진 정보 변경 로직 변경
  src/main/java/com/pickyfy/pickyfy/service/MagazineServiceImpl.java
  src/test/java/com/pickyfy/pickyfy/service/MagazineServiceImplTest.java
Labels: 🐛 bug

#74 [Refactor] Placeupdate 시 PlaceImage update 로직 수정
  src/main/java/com/pickyfy/pickyfy/domain/Place.java
  src/main/java/com/pickyfy/pickyfy/repository/PlaceImageRepository.java
  src/main/java/com/pickyfy/pickyfy/service/PlaceServiceImpl.java
Labels: ♻️ refactor

#87 [Feat] 토큰 재발급 API , 권한 기반 접근 제한 구현
  src/main/java/com/pickyfy/pickyfy/auth/filter/CustomLoginFilter.java
  src/main/java/com/pickyfy/pickyfy/auth/filter/JwtAuthFilter.java
  src/main/java/com/pickyfy/pickyfy/auth/handler/CustomAccessDeniedHandler.java
  src/main/java/com/pickyfy/pickyfy/auth/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/pickyfy/pickyfy/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/pickyfy/pickyfy/auth/oauth2/CustomAuthorizationRequestResolver.java
  src/main/java/com/pickyfy/pickyfy/common/config/SecurityConfig.java
  src/main/java/com/pickyfy/pickyfy/common/config/SwaggerConfig.java
  src/main/java/com/pickyfy/pickyfy/common/util/JwtUtil.java
  src/main/java/com/pickyfy/pickyfy/service/AuthService.java
  src/main/java/com/pickyfy/pickyfy/service/AuthServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/web/apiResponse/error/ErrorStatus.java
  src/main/java/com/pickyfy/pickyfy/web/controller/AuthController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/AuthControllerApi.java
  src/main/java/com/pickyfy/pickyfy/web/dto/response/AuthResponse.java
Labels: ✨ feature

#88 [Refactor] Place API userId 입력받는게 아닌 토큰으로 진행
  src/main/java/com/pickyfy/pickyfy/repository/SavedPlaceRepository.java
  src/main/java/com/pickyfy/pickyfy/repository/UserRepository.java
  src/main/java/com/pickyfy/pickyfy/service/PlaceService.java
  src/main/java/com/pickyfy/pickyfy/service/PlaceServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/web/controller/PlaceController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/PlaceControllerApi.java
  src/main/java/com/pickyfy/pickyfy/web/dto/response/PlaceSearchResponse.java
Labels: ♻️ refactor

#93 [feat] 주변 플레이스 검색 response에 인스타, 네이버 링크 필드 추가
  src/main/java/com/pickyfy/pickyfy/web/dto/response/NearbyPlaceResponse.java
Labels: ✨ feature

#78 [Fix]: 통합 테스트 테스트하기 위해 주석 해제
  .github/workflows/actions-dev.yml
  src/main/resources/application.yml
  src/test/java/com/pickyfy/pickyfy/PickyfyApplicationTests.java
  src/test/java/com/pickyfy/pickyfy/repository/PlaceRepositoryImplTest.java
  src/test/java/com/pickyfy/pickyfy/service/PlaceServiceImplTest.java
Labels: 🐛 bug

#96 [refactor] 로그인 성공 시 응답 body에 role 값 추가
  src/main/java/com/pickyfy/pickyfy/auth/filter/CustomLoginFilter.java
Labels: ♻️ refactor

#101 [Refactor] 소셜 로그인 서버측 리다이렉트 추가
  src/main/java/com/pickyfy/pickyfy/auth/handler/OAuth2SuccessHandler.java
Labels: ♻️ refactor

#102 [feat] PlaceService 테스트 코드 작성 및 저장된 플레이스 조회 null값 검증 추가
  src/main/java/com/pickyfy/pickyfy/service/PlaceServiceImpl.java
  src/test/java/com/pickyfy/pickyfy/service/PlaceServiceImplTest.java
Labels: ✨ feature

#117 [Refactor] 로그인 , 로그아웃 API 응답형식 변경
  src/main/java/com/pickyfy/pickyfy/auth/filter/CustomLoginFilter.java
  src/main/java/com/pickyfy/pickyfy/auth/filter/JwtAuthFilter.java
  src/main/java/com/pickyfy/pickyfy/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/pickyfy/pickyfy/common/config/SwaggerConfig.java
  src/main/java/com/pickyfy/pickyfy/common/util/TokenExtractor.java
  src/main/java/com/pickyfy/pickyfy/web/controller/AuthController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/AuthControllerApi.java
Labels: ♻️ refactor

#119 [feat] 로그인 상태 검증 API 구현
  src/main/java/com/pickyfy/pickyfy/auth/filter/JwtAuthFilter.java
  src/main/java/com/pickyfy/pickyfy/common/config/SecurityConfig.java
  src/main/java/com/pickyfy/pickyfy/common/util/JwtUtil.java
  src/main/java/com/pickyfy/pickyfy/service/AuthService.java
  src/main/java/com/pickyfy/pickyfy/service/AuthServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/web/controller/AuthController.java
  src/main/java/com/pickyfy/pickyfy/web/controller/AuthControllerApi.java
Labels: ✨ feature

#122 [feat] 주변 장소 검색 시 매거진 iconUrl도 포함하도록 추가
  src/main/java/com/pickyfy/pickyfy/web/dto/MagazineInfo.java
  src/main/java/com/pickyfy/pickyfy/web/dto/response/NearbyPlaceResponse.java
Labels: ✨ feature

#133 [Refactor] 배포 환경설정 추가
  src/main/java/com/pickyfy/pickyfy/auth/filter/CustomLoginFilter.java
  src/main/java/com/pickyfy/pickyfy/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/pickyfy/pickyfy/common/config/WebConfig.java
  src/main/java/com/pickyfy/pickyfy/web/controller/AuthController.java
Labels: ♻️ refactor

#135 [Bug] 도메인 주소 오류 수정
  src/main/java/com/pickyfy/pickyfy/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/pickyfy/pickyfy/common/config/WebConfig.java
Labels: 🐛 bug

#125 [Feature] S3 저장소와 DB 동기화 작업 구현
  src/main/java/com/pickyfy/pickyfy/PickyfyApplication.java
  src/main/java/com/pickyfy/pickyfy/repository/PlaceImageRepository.java
  src/main/java/com/pickyfy/pickyfy/service/ImageCleanupService.java
Labels: ✨ feature

#137 [Feature] 플레이스 조회 응답에 likeCount 추가
  src/main/java/com/pickyfy/pickyfy/domain/Place.java
  src/main/java/com/pickyfy/pickyfy/service/PlaceServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/web/dto/response/NearbyPlaceResponse.java
  src/main/java/com/pickyfy/pickyfy/web/dto/response/PlaceSearchResponse.java
  src/test/java/com/pickyfy/pickyfy/service/PlaceServiceImplTest.java
Labels: ✨ feature

#140 [Feat] Redis 캐싱 적용
  src/main/java/com/pickyfy/pickyfy/auth/filter/CustomLoginFilter.java
  src/main/java/com/pickyfy/pickyfy/auth/handler/OAuth2SuccessHandler.java
  src/main/java/com/pickyfy/pickyfy/common/Constant.java
  src/main/java/com/pickyfy/pickyfy/common/config/RedisConfig.java
  src/main/java/com/pickyfy/pickyfy/common/util/RedisUtil.java
  src/main/java/com/pickyfy/pickyfy/service/AuthServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/CategoryServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/EmailServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/MagazineServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/PlaceServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/service/UserServiceImpl.java
Labels: ✨ feature

#149 [refactor] 이메일 인증코드 전송을 @Async로 비동기 처리
  src/main/java/com/pickyfy/pickyfy/common/config/AsyncConfig.java
  src/main/java/com/pickyfy/pickyfy/service/EmailServiceImpl.java
  src/main/java/com/pickyfy/pickyfy/web/controller/AsyncEmailService.java
Labels: ♻️ refactor
